/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chomp;

import java.awt.Dimension;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import static jdk.nashorn.internal.objects.NativeRegExp.global;



/**
 *
 * @author bolat
 */
public class NewJFrame extends javax.swing.JFrame {

        
    

protected ImageIcon createIcon(String path) {
    URL imgURL = NewJFrame.class.getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL);
    } else {
        System.err.println("File not found " + path);
        return null;
    }
}
   
   //JButton[][] a1;
ImageIcon icon1 = createIcon("bmw.png");
        ImageIcon icon2 = createIcon("lamborghini.png");
        ImageIcon icon3 = createIcon("icon3.png");
    
   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
     
        
         
        initComponents();
        b1.setIcon(icon1);
        b2.setIcon(icon1);
        b3.setIcon(icon1);
        b4.setIcon(icon1);
        b5.setIcon(icon1);
        b6.setIcon(icon1);
        b7.setIcon(icon1);
        b8.setIcon(icon1);
        b9.setIcon(icon1);
        b10.setIcon(icon1);
        b11.setIcon(icon1);
        b12.setIcon(icon1);
        b13.setIcon(icon1);
        b14.setIcon(icon1);
        b15.setIcon(icon1);
        b16.setIcon(icon1);
        b17.setIcon(icon1);
        b18.setIcon(icon1);
        b19.setIcon(icon1);
        b20.setIcon(icon1);
        b21.setIcon(icon1);
        b22.setIcon(icon1);
        b24.setIcon(icon1);
        b23.setIcon(icon1);
        b25.setIcon(icon1);
        b26.setIcon(icon1);
        b27.setIcon(icon1);
        b28.setIcon(icon1);
        b29.setIcon(icon1);
        b30.setIcon(icon1);
        b31.setIcon(icon2);
        b32.setIcon(icon1);
        b33.setIcon(icon1);
        b36.setIcon(icon1);
        b35.setIcon(icon1);
        b34.setIcon(icon1);
        
         
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setAlignmentX(0.5F);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });

        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });

        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });

        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });

        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });

        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });

        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b34ActionPerformed(evt);
            }
        });

        b35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b35ActionPerformed(evt);
            }
        });

        b36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b36ActionPerformed(evt);
            }
        });

        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });

        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b7)
                                .addGap(18, 18, 18)
                                .addComponent(b8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b13)
                                .addGap(18, 18, 18)
                                .addComponent(b14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b1)
                                .addGap(10, 10, 10)
                                .addComponent(b2)
                                .addGap(18, 18, 18)
                                .addComponent(b3)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4)
                            .addComponent(b10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b11)
                                .addGap(18, 18, 18)
                                .addComponent(b12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b5)
                                .addGap(18, 18, 18)
                                .addComponent(b6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b31)
                                .addGap(18, 18, 18)
                                .addComponent(b32)
                                .addGap(18, 18, 18)
                                .addComponent(b33))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(b25)
                                    .addGap(18, 18, 18)
                                    .addComponent(b26)
                                    .addGap(18, 18, 18)
                                    .addComponent(b27))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b15)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b19)
                                        .addGap(18, 18, 18)
                                        .addComponent(b20)
                                        .addGap(18, 18, 18)
                                        .addComponent(b21)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b16)
                                        .addGap(20, 20, 20)
                                        .addComponent(b17))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b23)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b24)
                                    .addComponent(b18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(b34)
                                    .addGap(18, 18, 18)
                                    .addComponent(b35)
                                    .addGap(18, 18, 18)
                                    .addComponent(b36))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(b28)
                                    .addGap(18, 18, 18)
                                    .addComponent(b29)
                                    .addGap(18, 18, 18)
                                    .addComponent(b30))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b10)
                    .addComponent(b9)
                    .addComponent(b8)
                    .addComponent(b7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b17)
                    .addComponent(b14)
                    .addComponent(b13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b18)
                        .addComponent(b16)
                        .addComponent(b15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(b21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b23)
                        .addComponent(b24)
                        .addComponent(b22)
                        .addComponent(b20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(b19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b25)
                    .addComponent(b26)
                    .addComponent(b27)
                    .addComponent(b28)
                    .addComponent(b29)
                    .addComponent(b30))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b36)
                    .addComponent(b35)
                    .addComponent(b34)
                    .addComponent(b33)
                    .addComponent(b32)
                    .addComponent(b31))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
       JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
       b1.setIcon(icon3);
       for (int i = 0; i < 1; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
       
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 1; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 2; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        // TODO add your handling code here:
       
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 6; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }

        
    }//GEN-LAST:event_b32ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 2; i++) {
           for (int j = 0; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 2; i++) {
           for (int j = 2; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 2; i++) {
           for (int j = 3; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 2; i++) {
           for (int j = 4; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 2; i++) {
           for (int j = 5; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 3; i++) {
           for (int j = 0; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b13ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 1; i++) {
           for (int j = 2; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 1; i++) {
           for (int j = 3; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 1; i++) {
           for (int j = 4; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 1; i++) {
           for (int j = 5; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 3; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 3; i++) {
           for (int j = 2; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 3; i++) {
           for (int j = 3; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 3; i++) {
           for (int j = 4; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 3; i++) {
           for (int j = 5; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 4; i++) {
           for (int j = 0; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 4; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 4; i++) {
           for (int j = 2; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b21ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 4; i++) {
           for (int j = 3; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b22ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 4; i++) {
           for (int j = 4; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 4; i++) {
           for (int j = 5; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b24ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 5; i++) {
           for (int j = 0; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b25ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 5; i++) {
           for (int j = 1; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b26ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 5; i++) {
           for (int j = 2; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b27ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 5; i++) {
           for (int j = 3; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b28ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 5; i++) {
           for (int j = 4; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b29ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 5; i++) {
           for (int j = 5; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b30ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        // TODO add your handling code here:
        
        System.out.println("you lose");    
        
    }//GEN-LAST:event_b31ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b36,b35,b34}};
        for (int i = 0; i < 6; i++) {
           for (int j = 2; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b33ActionPerformed

    private void b34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b34ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b34,b35,b36}};
        for (int i = 0; i < 6; i++) {
           for (int j = 3; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b34ActionPerformed

    private void b35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b35ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b24,b23},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b34,b35,b36}};
        for (int i = 0; i < 6; i++) {
           for (int j = 4; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b35ActionPerformed

    private void b36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b36ActionPerformed
        // TODO add your handling code here:
        JButton  a1[][] = {{b1,b2,b3,b4,b5,b6},
                                {b7,b8,b9,b10,b11,b12},
                                {b13,b14,b15,b16,b17,b18},
                                {b19,b20,b21,b22,b23,b24},
                                {b25,b26,b27,b28,b29,b30},
                                {b31,b32,b33,b34,b35,b36}};
        for (int i = 0; i < 6; i++) {
           for (int j = 5; j < 6; j++) {
               
                a1[i][j].setIcon(icon3);
            }
        }
    }//GEN-LAST:event_b36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new NewJFrame().setVisible(true);
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
